=== justjake/sqlite3-parser-js/generated/json-schema/v1/parser.dev.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "claude-lemon/parser.dev/v1",
  "title": "parser.dev",
  "type": "object",
  "required": [
    "constants",
    "tables",
    "symbols",
    "rules"
  ],
  "properties": {
    "constants": {
      "type": "object",
      "required": [
        "YYNSTATE",
        "YYNRULE",
        "YYNTOKEN",
        "YYNSYMBOL",
        "YY_MAX_SHIFT",
        "YY_MIN_SHIFTREDUCE",
        "YY_MAX_SHIFTREDUCE",
        "YY_ERROR_ACTION",
        "YY_ACCEPT_ACTION",
        "YY_NO_ACTION",
        "YY_MIN_REDUCE",
        "YY_MAX_REDUCE",
        "YY_ACTTAB_COUNT",
        "YY_SHIFT_COUNT",
        "YY_REDUCE_COUNT",
        "YYWILDCARD",
        "YYFALLBACK"
      ],
      "properties": {
        "YYNSTATE": {
          "type": "integer"
        },
        "YYNRULE": {
          "type": "integer"
        },
        "YYNTOKEN": {
          "type": "integer"
        },
        "YYNSYMBOL": {
          "type": "integer"
        },
        "YY_MAX_SHIFT": {
          "type": "integer"
        },
        "YY_MIN_SHIFTREDUCE": {
          "type": "integer"
        },
        "YY_MAX_SHIFTREDUCE": {
          "type": "integer"
        },
        "YY_ERROR_ACTION": {
          "type": "integer"
        },
        "YY_ACCEPT_ACTION": {
          "type": "integer"
        },
        "YY_NO_ACTION": {
          "type": "integer"
        },
        "YY_MIN_REDUCE": {
          "type": "integer"
        },
        "YY_MAX_REDUCE": {
          "type": "integer"
        },
        "YY_ACTTAB_COUNT": {
          "type": "integer"
        },
        "YY_SHIFT_COUNT": {
          "type": "integer"
        },
        "YY_REDUCE_COUNT": {
          "type": "integer"
        },
        "YYWILDCARD": {
          "type": "integer"
        },
        "YYFALLBACK": {
          "anyOf": [
            {
              "type": "number",
              "const": 0
            },
            {
              "type": "number",
              "const": 1
            }
          ]
        }
      },
      "additionalProperties": true
    },
    "tables": {
      "type": "object",
      "required": [
        "yy_action",
        "yy_lookahead",
        "yy_shift_ofst",
        "yy_reduce_ofst",
        "yy_default"
      ],
      "properties": {
        "yy_action": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "yy_lookahead": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 0,
            "title": "SymbolId"
          }
        },
        "yy_shift_ofst": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "yy_reduce_ofst": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "yy_default": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "yyFallback": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 0,
            "title": "TokenId"
          }
        }
      },
      "additionalProperties": true
    },
    "symbols": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name",
          "isTerminal"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 0,
            "title": "SymbolId"
          },
          "name": {
            "type": "string"
          },
          "isTerminal": {
            "type": "boolean"
          }
        },
        "additionalProperties": true
      }
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "lhs",
          "lhsName",
          "nrhs",
          "rhs",
          "doesReduce"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 0,
            "title": "RuleId"
          },
          "lhs": {
            "type": "integer",
            "minimum": 0,
            "title": "SymbolId"
          },
          "lhsName": {
            "type": "string"
          },
          "nrhs": {
            "type": "integer"
          },
          "rhs": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "pos"
              ],
              "properties": {
                "pos": {
                  "type": "integer"
                },
                "symbol": {
                  "type": "integer",
                  "minimum": 0,
                  "title": "SymbolId"
                },
                "multi": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": [
                      "symbol",
                      "name"
                    ],
                    "properties": {
                      "symbol": {
                        "type": "integer",
                        "minimum": 0,
                        "title": "SymbolId"
                      },
                      "name": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": true
                  }
                },
                "name": {
                  "type": "string"
                }
              },
              "additionalProperties": true
            }
          },
          "doesReduce": {
            "type": "boolean"
          }
        },
        "additionalProperties": true
      }
    }
  },
  "additionalProperties": true
}

=== justjake/sqlite3-parser-js/generated/3.54.0/parser.prod.json
{"constants":{"YYNSTATE":607,"YYNRULE":414,"YYNTOKEN":188,"YYNSYMBOL":323,"YY_MAX_SHIFT":606,"YY_MIN_SHIFTREDUCE":875,"YY_MAX_SHIFTREDUCE":1288,"YY_ERROR_ACTION":1289,"YY_ACCEPT_ACTION":1290,"YY_NO_ACTION":1291,"YY_MIN_REDUCE":1292,"YY_MAX_REDUCE":1705,"YY_ACTTAB_COUNT":2535,"YY_SHIFT_COUNT":606,"YY_REDUCE_COUNT":426,"YYWILDCARD":103,"YYFALLBACK":1},"symbols":[{"id":0,"name":"$","isTerminal":true},{"id":1,"name":"SEMI","isTerminal":true},{"id":2,"name":"EXPLAIN","isTerminal":true},{"id":3,"name":"QUERY","isTerminal":true},{"id":4,"name":"PLAN","isTerminal":true},{"id":5,"name":"BEGIN","isTerminal":true},{"id":6,"name":"TRANSACTION","isTerminal":true},{"id":7,"name":"DEFERRED","isTerminal":true},{"id":8,"name":"IMMEDIATE","isTerminal":true},{"id":9,"name":"EXCLUSIVE","isTerminal":true},{"id":10,"name":"COMMIT","isTerminal":true},{"id":11,"name":"END","isTerminal":true},{"id":12,"name":"ROLLBACK","isTerminal":true},{"id":13,"name":"SAVEPOINT","isTerminal":true},{"id":14,"name":"RELEASE","isTerminal":true},{"id":15,"name":"TO","isTerminal":true},{"id":16,"name":"TABLE","isTerminal":true},{"id":17,"name":"CREATE","isTerminal":true},{"id":18,"name":"IF","isTerminal":true},{"id":19,"name":"NOT","isTerminal":true},{"id":20,"name":"EXISTS","isTerminal":true},{"id":21,"name":"TEMP","isTerminal":true},{"id":22,"name":"LP","isTerminal":true},{"id":23,"name":"RP","isTerminal":true},{"id":24,"name":"AS","isTerminal":true},{"id":25,"name":"COMMA","isTerminal":true},{"id":26,"name":"WITHOUT","isTerminal":true},{"id":27,"name":"ABORT","isTerminal":true},{"id":28,"name":"ACTION","isTerminal":true},{"id":29,"name":"AFTER","isTerminal":true},{"id":30,"name":"ANALYZE","isTerminal":true},{"id":31,"name":"ASC","isTerminal":true},{"id":32,"name":"ATTACH","isTerminal":true},{"id":33,"name":"BEFORE","isTerminal":true},{"id":34,"name":"BY","isTerminal":true},{"id":35,"name":"CASCADE","isTerminal":true},{"id":36,"name":"CAST","isTerminal":true},{"id":37,"name":"CONFLICT","isTerminal":true},{"id":38,"name":"DATABASE","isTerminal":true},{"id":39,"name":"DESC","isTerminal":true},{"id":40,"name":"DETACH","isTerminal":true},{"id":41,"name":"EACH","isTerminal":true},{"id":42,"name":"FAIL","isTerminal":true},{"id":43,"name":"OR","isTerminal":true},{"id":44,"name":"AND","isTerminal":true},{"id":45,"name":"IS","isTerminal":true},{"id":46,"name":"ISNOT","isTerminal":true},{"id":47,"name":"MATCH","isTerminal":true},{"id":48,"name":"LIKE_KW","isTerminal":true},{"id":49,"name":"BETWEEN","isTerminal":true},{"id":50,"name":"IN","isTerminal":true},{"id":51,"name":"ISNULL","isTerminal":true},{"id":52,"name":"NOTNULL","isTerminal":true},{"id":53,"name":"NE","isTerminal":true},{"id":54,"name":"EQ","isTerminal":true},{"id":55,"name":"GT","isTerminal":true},{"id":56,"name":"LE","isTerminal":true},{"id":57,"name":"LT","isTerminal":true},{"id":58,"name":"GE","isTerminal":true},{"id":59,"name":"ESCAPE","isTerminal":true},{"id":60,"name":"ID","isTerminal":true},{"id":61,"name":"COLUMNKW","isTerminal":true},{"id":62,"name":"DO","isTerminal":true},{"id":63,"name":"FOR","isTerminal":true},{"id":64,"name":"IGNORE","isTerminal":true},{"id":65,"name":"INITIALLY","isTerminal":true},{"id":66,"name":"INSTEAD","isTerminal":true},{"id":67,"name":"NO","isTerminal":true},{"id":68,"name":"KEY","isTerminal":true},{"id":69,"name":"OF","isTerminal":true},{"id":70,"name":"OFFSET","isTerminal":true},{"id":71,"name":"PRAGMA","isTerminal":true},{"id":72,"name":"RAISE","isTerminal":true},{"id":73,"name":"RECURSIVE","isTerminal":true},{"id":74,"name":"REPLACE","isTerminal":true},{"id":75,"name":"RESTRICT","isTerminal":true},{"id":76,"name":"ROW","isTerminal":true},{"id":77,"name":"ROWS","isTerminal":true},{"id":78,"name":"TRIGGER","isTerminal":true},{"id":79,"name":"VACUUM","isTerminal":true},{"id":80,"name":"VIEW","isTerminal":true},{"id":81,"name":"VIRTUAL","isTerminal":true},{"id":82,"name":"WITH","isTerminal":true},{"id":83,"name":"NULLS","isTerminal":true},{"id":84,"name":"FIRST","isTerminal":true},{"id":85,"name":"LAST","isTerminal":true},{"id":86,"name":"CURRENT","isTerminal":true},{"id":87,"name":"FOLLOWING","isTerminal":true},{"id":88,"name":"PARTITION","isTerminal":true},{"id":89,"name":"PRECEDING","isTerminal":true},{"id":90,"name":"RANGE","isTerminal":true},{"id":91,"name":"UNBOUNDED","isTerminal":true},{"id":92,"name":"EXCLUDE","isTerminal":true},{"id":93,"name":"GROUPS","isTerminal":true},{"id":94,"name":"OTHERS","isTerminal":true},{"id":95,"name":"TIES","isTerminal":true},{"id":96,"name":"WITHIN","isTerminal":true},{"id":97,"name":"GENERATED","isTerminal":true},{"id":98,"name":"ALWAYS","isTerminal":true},{"id":99,"name":"MATERIALIZED","isTerminal":true},{"id":100,"name":"REINDEX","isTerminal":true},{"id":101,"name":"RENAME","isTerminal":true},{"id":102,"name":"CTIME_KW","isTerminal":true},{"id":103,"name":"ANY","isTerminal":true},{"id":104,"name":"BITAND","isTerminal":true},{"id":105,"name":"BITOR","isTerminal":true},{"id":106,"name":"LSHIFT","isTerminal":true},{"id":107,"name":"RSHIFT","isTerminal":true},{"id":108,"name":"PLUS","isTerminal":true},{"id":109,"name":"MINUS","isTerminal":true},{"id":110,"name":"STAR","isTerminal":true},{"id":111,"name":"SLASH","isTerminal":true},{"id":112,"name":"REM","isTerminal":true},{"id":113,"name":"CONCAT","isTerminal":true},{"id":114,"name":"PTR","isTerminal":true},{"id":115,"name":"COLLATE","isTerminal":true},{"id":116,"name":"BITNOT","isTerminal":true},{"id":117,"name":"ON","isTerminal":true},{"id":118,"name":"INDEXED","isTerminal":true},{"id":119,"name":"STRING","isTerminal":true},{"id":120,"name":"JOIN_KW","isTerminal":true},{"id":121,"name":"CONSTRAINT","isTerminal":true},{"id":122,"name":"DEFAULT","isTerminal":true},{"id":123,"name":"NULL","isTerminal":true},{"id":124,"name":"PRIMARY","isTerminal":true},{"id":125,"name":"UNIQUE","isTerminal":true},{"id":126,"name":"CHECK","isTerminal":true},{"id":127,"name":"REFERENCES","isTerminal":true},{"id":128,"name":"AUTOINCR","isTerminal":true},{"id":129,"name":"INSERT","isTerminal":true},{"id":130,"name":"DELETE","isTerminal":true},{"id":131,"name":"UPDATE","isTerminal":true},{"id":132,"name":"SET","isTerminal":true},{"id":133,"name":"DEFERRABLE","isTerminal":true},{"id":134,"name":"FOREIGN","isTerminal":true},{"id":135,"name":"DROP","isTerminal":true},{"id":136,"name":"UNION","isTerminal":true},{"id":137,"name":"ALL","isTerminal":true},{"id":138,"name":"EXCEPT","isTerminal":true},{"id":139,"name":"INTERSECT","isTerminal":true},{"id":140,"name":"SELECT","isTerminal":true},{"id":141,"name":"VALUES","isTerminal":true},{"id":142,"name":"DISTINCT","isTerminal":true},{"id":143,"name":"DOT","isTerminal":true},{"id":144,"name":"FROM","isTerminal":true},{"id":145,"name":"JOIN","isTerminal":true},{"id":146,"name":"USING","isTerminal":true},{"id":147,"name":"ORDER","isTerminal":true},{"id":148,"name":"GROUP","isTerminal":true},{"id":149,"name":"HAVING","isTerminal":true},{"id":150,"name":"LIMIT","isTerminal":true},{"id":151,"name":"WHERE","isTerminal":true},{"id":152,"name":"RETURNING","isTerminal":true},{"id":153,"name":"INTO","isTerminal":true},{"id":154,"name":"NOTHING","isTerminal":true},{"id":155,"name":"FLOAT","isTerminal":true},{"id":156,"name":"BLOB","isTerminal":true},{"id":157,"name":"INTEGER","isTerminal":true},{"id":158,"name":"VARIABLE","isTerminal":true},{"id":159,"name":"CASE","isTerminal":true},{"id":160,"name":"WHEN","isTerminal":true},{"id":161,"name":"THEN","isTerminal":true},{"id":162,"name":"ELSE","isTerminal":true},{"id":163,"name":"INDEX","isTerminal":true},{"id":164,"name":"ALTER","isTerminal":true},{"id":165,"name":"ADD","isTerminal":true},{"id":166,"name":"WINDOW","isTerminal":true},{"id":167,"name":"OVER","isTerminal":true},{"id":168,"name":"FILTER","isTerminal":true},{"id":169,"name":"COLUMN","isTerminal":true},{"id":170,"name":"AGG_FUNCTION","isTerminal":true},{"id":171,"name":"AGG_COLUMN","isTerminal":true},{"id":172,"name":"TRUEFALSE","isTerminal":true},{"id":173,"name":"FUNCTION","isTerminal":true},{"id":174,"name":"UPLUS","isTerminal":true},{"id":175,"name":"UMINUS","isTerminal":true},{"id":176,"name":"TRUTH","isTerminal":true},{"id":177,"name":"REGISTER","isTerminal":true},{"id":178,"name":"VECTOR","isTerminal":true},{"id":179,"name":"SELECT_COLUMN","isTerminal":true},{"id":180,"name":"IF_NULL_ROW","isTerminal":true},{"id":181,"name":"ASTERISK","isTerminal":true},{"id":182,"name":"SPAN","isTerminal":true},{"id":183,"name":"ERROR","isTerminal":true},{"id":184,"name":"QNUMBER","isTerminal":true},{"id":185,"name":"SPACE","isTerminal":true},{"id":186,"name":"COMMENT","isTerminal":true},{"id":187,"name":"ILLEGAL","isTerminal":true},{"id":188,"name":"input","isTerminal":false},{"id":189,"name":"cmdlist","isTerminal":false},{"id":190,"name":"ecmd","isTerminal":false},{"id":191,"name":"cmdx","isTerminal":false},{"id":192,"name":"explain","isTerminal":false},{"id":193,"name":"cmd","isTerminal":false},{"id":194,"name":"transtype","isTerminal":false},{"id":195,"name":"trans_opt","isTerminal":false},{"id":196,"name":"nm","isTerminal":false},{"id":197,"name":"savepoint_opt","isTerminal":false},{"id":198,"name":"create_table","isTerminal":false},{"id":199,"name":"create_table_args","isTerminal":false},{"id":200,"name":"createkw","isTerminal":false},{"id":201,"name":"temp","isTerminal":false},{"id":202,"name":"ifnotexists","isTerminal":false},{"id":203,"name":"dbnm","isTerminal":false},{"id":204,"name":"columnlist","isTerminal":false},{"id":205,"name":"conslist_opt","isTerminal":false},{"id":206,"name":"table_option_set","isTerminal":false},{"id":207,"name":"select","isTerminal":false},{"id":208,"name":"table_option","isTerminal":false},{"id":209,"name":"columnname","isTerminal":false},{"id":210,"name":"carglist","isTerminal":false},{"id":211,"name":"typetoken","isTerminal":false},{"id":212,"name":"typename","isTerminal":false},{"id":213,"name":"signed","isTerminal":false},{"id":214,"name":"plus_num","isTerminal":false},{"id":215,"name":"minus_num","isTerminal":false},{"id":
